### ISSUE TITLE
複数リポジトリを同時にコミットすると例外が発生する？

### ISSUE THREAD

**Issue by jeisi** [jeisi/BerettaCommitTool2#41]
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index: 4, Size: 0
	at java.base/java.util.AbstractList.rangeCheckForAdd(AbstractList.java:632)
	at java.base/java.util.AbstractList.addAll(AbstractList.java:267)
	at javafx.base/javafx.collections.ModifiableObservableListBase.addAll(ModifiableObservableListBase.java:110)
	at com.xrea.jeisi.berettacommittool2.aggregatedobservablearraylist.AggregatedObservableArrayList$InternalListModificationListener.onChanged(AggregatedObservableArrayList.java:169)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.base/javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	at com.xrea.jeisi.berettacommittool2.gitstatuspane.GitStatusPane.lambda$refreshRepository$10(GitStatusPane.java:261)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by jeisi** [comment]
多分修正された。
